// =============================================================
// scripts/setup-local.js
// Plantea — Local Network Setup Script
// =============================================================
// Purpose: Auto-configure frontend .env with PC's WiFi IP address
//   so mobile phones on the same network can reach the backend.
//
// Usage: node plantea-frontend/scripts/setup-local.js
//   or:  npm run setup (from project root)
// =============================================================

const os = require('os');
const fs = require('fs');
const path = require('path');

/**
 * Get the local WiFi IP address of this PC.
 * Finds the first non-internal IPv4 address.
 */
function getLocalIP() {
  const nets = os.networkInterfaces();
  
  for (const iface of Object.values(nets)) {
    for (const net of iface) {
      // Skip internal (loopback) and non-IPv4 addresses
      if (net.family === 'IPv4' && !net.internal) {
        return net.address;
      }
    }
  }
  
  return 'localhost';
}

// Get local IP
const ip = getLocalIP();
const backendPort = 3000;
const frontendPort = 8081;

// Path to frontend .env file
const envPath = path.join(__dirname, '..', '.env');

// Generate .env content
const envLines = [
  '# AUTO-GENERATED by scripts/setup-local.js — do not edit manually',
  '# Run "npm run setup" to regenerate this file',
  '',
  '# Backend API Configuration',
  `EXPO_PUBLIC_API_BASE_URL=http://${ip}:${backendPort}/api`,
  'EXPO_PUBLIC_API_TIMEOUT=10000',
  '',
  '# For production deployment, change to your Railway URL:',
  '# EXPO_PUBLIC_API_BASE_URL=https://your-app.railway.app/api',
];

// Write .env file
fs.writeFileSync(envPath, envLines.join('\n'));

// Display success message with instructions
console.log('');
console.log('✅  Plantea Local Network Setup Complete');
console.log('========================================');
console.log('');
console.log('📡 Network Configuration:');
console.log(`   PC IP Address:    ${ip}`);
console.log(`   Backend API:      http://${ip}:${backendPort}/api`);
console.log(`   Health Check:     http://${ip}:${backendPort}/health`);
console.log(`   Mobile Frontend:  http://${ip}:${frontendPort}`);
console.log(`   Expo Go URL:      exp://${ip}:${frontendPort}`);
console.log('');
console.log('📱 STEPS TO CONNECT YOUR PHONE:');
console.log('   1. Make sure phone is on same WiFi as this PC');
console.log('   2. Install Expo Go from App Store or Play Store');
console.log('   3. Open Expo Go on your phone');
console.log(`   4. Tap "Enter URL manually" → type: exp://${ip}:${frontendPort}`);
console.log('      OR scan the QR code that appears in Terminal 2');
console.log('');
console.log('🚀 Next Steps:');
console.log('   Terminal 1: npm run backend   (starts backend server)');
console.log('   Terminal 2: npm run frontend  (starts Expo with QR code)');
console.log('   OR:         npm run dev       (starts both at once)');
console.log('');
console.log('📝 Note: .env file updated at:');
console.log(`   ${envPath}`);
console.log('');
